Option Strict Off

Namespace USR_USP_CONSTITUENTPHOTOANALYSIS_UPSERT

    '*****************************************************************
    'Generated by SPCodeGen © 2003 Blackbaud CoreTech
    '*****************************************************************
#Region "Parameter Specification"
    'Name                         Type                Size        Direction
    '@RETURN_VALUE                int                             Return value
    '@CONSTITUENTID               uniqueidentifier                In
    '@PREDICTEDGENDERCODE         tinyint                         In
    '@ESTIMATEDAGE                int                             In
    '@ANGERRATING                 decimal             (20, 4)     In
    '@CONTEMPTRATING              decimal             (20, 4)     In
    '@DISGUSTRATING               decimal             (20, 4)     In
    '@FEARRATING                  decimal             (20, 4)     In
    '@HAPPINESSRATING             decimal             (20, 4)     In
    '@NEUTRALRATING               decimal             (20, 4)     In
    '@SADNESSRATING               decimal             (20, 4)     In
    '@SURPRISERATING              decimal             (20, 4)     In
    '@CHANGEAGENTID               uniqueidentifier                In
    '@CURRENTDATE                 datetime                        In
#End Region

    'SP TYPE: Stored Procedure - no resultset


    <System.CodeDom.Compiler.GeneratedCodeAttribute("SPCodeGen", "2.0.0.0")>
    Public Module WrapperRoutines

        Public Function CreateSQLCommand(ByVal conn As System.Data.SqlClient.SqlConnection, ByVal [CONSTITUENTID] As Nullable(Of System.Guid), ByVal [PREDICTEDGENDERCODE] As Nullable(Of Byte), ByVal [ESTIMATEDAGE] As Nullable(Of Integer), ByVal [ANGERRATING] As Nullable(Of Decimal), ByVal [CONTEMPTRATING] As Nullable(Of Decimal), ByVal [DISGUSTRATING] As Nullable(Of Decimal), ByVal [FEARRATING] As Nullable(Of Decimal), ByVal [HAPPINESSRATING] As Nullable(Of Decimal), ByVal [NEUTRALRATING] As Nullable(Of Decimal), ByVal [SADNESSRATING] As Nullable(Of Decimal), ByVal [SURPRISERATING] As Nullable(Of Decimal), ByVal [CHANGEAGENTID] As Nullable(Of System.Guid), ByVal [CURRENTDATE] As Nullable(Of Date), Optional ByVal timeout As Integer = 0) As System.Data.SqlClient.SqlCommand

            Dim cmd As System.Data.SqlClient.SqlCommand = conn.CreateCommand
            If timeout = 0 Then
                cmd.CommandTimeout = Config.DefaultNonQueryTimeout
            Else
                cmd.CommandTimeout = timeout
            End If
            cmd.CommandType = CommandType.StoredProcedure
            cmd.CommandText = "dbo.USR_USP_CONSTITUENTPHOTOANALYSIS_UPSERT"

            Dim p As System.Data.SqlClient.SqlParameter

            '@RETURN_VALUE
            p = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int)
            p.Direction = ParameterDirection.ReturnValue
            p.Value = 0


            '@CONSTITUENTID
            If [CONSTITUENTID].HasValue Then
                cmd.Parameters.AddWithValue("@CONSTITUENTID", [CONSTITUENTID].Value)
            Else
                cmd.Parameters.AddWithValue("@CONSTITUENTID", System.DBNull.Value).SqlDbType = SqlDbType.uniqueidentifier
            End If


            '@PREDICTEDGENDERCODE
            If [PREDICTEDGENDERCODE].HasValue Then
                cmd.Parameters.AddWithValue("@PREDICTEDGENDERCODE", [PREDICTEDGENDERCODE].Value)
            Else
                cmd.Parameters.AddWithValue("@PREDICTEDGENDERCODE", System.DBNull.Value).SqlDbType = SqlDbType.tinyint
            End If


            '@ESTIMATEDAGE
            If [ESTIMATEDAGE].HasValue Then
                cmd.Parameters.AddWithValue("@ESTIMATEDAGE", [ESTIMATEDAGE].Value)
            Else
                cmd.Parameters.AddWithValue("@ESTIMATEDAGE", System.DBNull.Value).SqlDbType = SqlDbType.int
            End If


            '@ANGERRATING
            If [ANGERRATING].HasValue Then
                cmd.Parameters.AddWithValue("@ANGERRATING", [ANGERRATING].Value)
            Else
                cmd.Parameters.AddWithValue("@ANGERRATING", System.DBNull.Value).SqlDbType = SqlDbType.decimal
            End If


            '@CONTEMPTRATING
            If [CONTEMPTRATING].HasValue Then
                cmd.Parameters.AddWithValue("@CONTEMPTRATING", [CONTEMPTRATING].Value)
            Else
                cmd.Parameters.AddWithValue("@CONTEMPTRATING", System.DBNull.Value).SqlDbType = SqlDbType.decimal
            End If


            '@DISGUSTRATING
            If [DISGUSTRATING].HasValue Then
                cmd.Parameters.AddWithValue("@DISGUSTRATING", [DISGUSTRATING].Value)
            Else
                cmd.Parameters.AddWithValue("@DISGUSTRATING", System.DBNull.Value).SqlDbType = SqlDbType.decimal
            End If


            '@FEARRATING
            If [FEARRATING].HasValue Then
                cmd.Parameters.AddWithValue("@FEARRATING", [FEARRATING].Value)
            Else
                cmd.Parameters.AddWithValue("@FEARRATING", System.DBNull.Value).SqlDbType = SqlDbType.decimal
            End If


            '@HAPPINESSRATING
            If [HAPPINESSRATING].HasValue Then
                cmd.Parameters.AddWithValue("@HAPPINESSRATING", [HAPPINESSRATING].Value)
            Else
                cmd.Parameters.AddWithValue("@HAPPINESSRATING", System.DBNull.Value).SqlDbType = SqlDbType.decimal
            End If


            '@NEUTRALRATING
            If [NEUTRALRATING].HasValue Then
                cmd.Parameters.AddWithValue("@NEUTRALRATING", [NEUTRALRATING].Value)
            Else
                cmd.Parameters.AddWithValue("@NEUTRALRATING", System.DBNull.Value).SqlDbType = SqlDbType.decimal
            End If


            '@SADNESSRATING
            If [SADNESSRATING].HasValue Then
                cmd.Parameters.AddWithValue("@SADNESSRATING", [SADNESSRATING].Value)
            Else
                cmd.Parameters.AddWithValue("@SADNESSRATING", System.DBNull.Value).SqlDbType = SqlDbType.decimal
            End If


            '@SURPRISERATING
            If [SURPRISERATING].HasValue Then
                cmd.Parameters.AddWithValue("@SURPRISERATING", [SURPRISERATING].Value)
            Else
                cmd.Parameters.AddWithValue("@SURPRISERATING", System.DBNull.Value).SqlDbType = SqlDbType.decimal
            End If


            '@CHANGEAGENTID
            If [CHANGEAGENTID].HasValue Then
                cmd.Parameters.AddWithValue("@CHANGEAGENTID", [CHANGEAGENTID].Value)
            Else
                cmd.Parameters.AddWithValue("@CHANGEAGENTID", System.DBNull.Value).SqlDbType = SqlDbType.uniqueidentifier
            End If


            '@CURRENTDATE
            If [CURRENTDATE].HasValue Then
                cmd.Parameters.AddWithValue("@CURRENTDATE", [CURRENTDATE].Value)
            Else
                cmd.Parameters.AddWithValue("@CURRENTDATE", System.DBNull.Value).SqlDbType = SqlDbType.datetime
            End If

            Return cmd
        End Function

        Public Function ExecuteNonQuery(ByVal conn As System.Data.SqlClient.SqlConnection, ByVal [CONSTITUENTID] As Nullable(Of System.Guid), ByVal [PREDICTEDGENDERCODE] As Nullable(Of Byte), ByVal [ESTIMATEDAGE] As Nullable(Of Integer), ByVal [ANGERRATING] As Nullable(Of Decimal), ByVal [CONTEMPTRATING] As Nullable(Of Decimal), ByVal [DISGUSTRATING] As Nullable(Of Decimal), ByVal [FEARRATING] As Nullable(Of Decimal), ByVal [HAPPINESSRATING] As Nullable(Of Decimal), ByVal [NEUTRALRATING] As Nullable(Of Decimal), ByVal [SADNESSRATING] As Nullable(Of Decimal), ByVal [SURPRISERATING] As Nullable(Of Decimal), ByVal [CHANGEAGENTID] As Nullable(Of System.Guid), ByVal [CURRENTDATE] As Nullable(Of Date)) As Integer
            Return ExecuteNonQuery(conn, [CONSTITUENTID], [PREDICTEDGENDERCODE], [ESTIMATEDAGE], [ANGERRATING], [CONTEMPTRATING], [DISGUSTRATING], [FEARRATING], [HAPPINESSRATING], [NEUTRALRATING], [SADNESSRATING], [SURPRISERATING], [CHANGEAGENTID], [CURRENTDATE], 0, 0, Nothing)
        End Function

        Public Function ExecuteNonQuery(ByVal conn As System.Data.SqlClient.SqlConnection, ByVal [CONSTITUENTID] As Nullable(Of System.Guid), ByVal [PREDICTEDGENDERCODE] As Nullable(Of Byte), ByVal [ESTIMATEDAGE] As Nullable(Of Integer), ByVal [ANGERRATING] As Nullable(Of Decimal), ByVal [CONTEMPTRATING] As Nullable(Of Decimal), ByVal [DISGUSTRATING] As Nullable(Of Decimal), ByVal [FEARRATING] As Nullable(Of Decimal), ByVal [HAPPINESSRATING] As Nullable(Of Decimal), ByVal [NEUTRALRATING] As Nullable(Of Decimal), ByVal [SADNESSRATING] As Nullable(Of Decimal), ByVal [SURPRISERATING] As Nullable(Of Decimal), ByVal [CHANGEAGENTID] As Nullable(Of System.Guid), ByVal [CURRENTDATE] As Nullable(Of Date), ByRef returnIntValue As Integer) As Integer
            Return ExecuteNonQuery(conn, [CONSTITUENTID], [PREDICTEDGENDERCODE], [ESTIMATEDAGE], [ANGERRATING], [CONTEMPTRATING], [DISGUSTRATING], [FEARRATING], [HAPPINESSRATING], [NEUTRALRATING], [SADNESSRATING], [SURPRISERATING], [CHANGEAGENTID], [CURRENTDATE], returnIntValue, 0, Nothing)
        End Function

        Public Function ExecuteNonQuery(ByVal conn As System.Data.SqlClient.SqlConnection, ByVal [CONSTITUENTID] As Nullable(Of System.Guid), ByVal [PREDICTEDGENDERCODE] As Nullable(Of Byte), ByVal [ESTIMATEDAGE] As Nullable(Of Integer), ByVal [ANGERRATING] As Nullable(Of Decimal), ByVal [CONTEMPTRATING] As Nullable(Of Decimal), ByVal [DISGUSTRATING] As Nullable(Of Decimal), ByVal [FEARRATING] As Nullable(Of Decimal), ByVal [HAPPINESSRATING] As Nullable(Of Decimal), ByVal [NEUTRALRATING] As Nullable(Of Decimal), ByVal [SADNESSRATING] As Nullable(Of Decimal), ByVal [SURPRISERATING] As Nullable(Of Decimal), ByVal [CHANGEAGENTID] As Nullable(Of System.Guid), ByVal [CURRENTDATE] As Nullable(Of Date), ByRef returnIntValue As Integer, ByVal timeout As Integer) As Integer
            Return ExecuteNonQuery(conn, [CONSTITUENTID], [PREDICTEDGENDERCODE], [ESTIMATEDAGE], [ANGERRATING], [CONTEMPTRATING], [DISGUSTRATING], [FEARRATING], [HAPPINESSRATING], [NEUTRALRATING], [SADNESSRATING], [SURPRISERATING], [CHANGEAGENTID], [CURRENTDATE], returnIntValue, timeout, Nothing)
        End Function

        Public Function ExecuteNonQuery(ByVal conn As System.Data.SqlClient.SqlConnection, ByVal [CONSTITUENTID] As Nullable(Of System.Guid), ByVal [PREDICTEDGENDERCODE] As Nullable(Of Byte), ByVal [ESTIMATEDAGE] As Nullable(Of Integer), ByVal [ANGERRATING] As Nullable(Of Decimal), ByVal [CONTEMPTRATING] As Nullable(Of Decimal), ByVal [DISGUSTRATING] As Nullable(Of Decimal), ByVal [FEARRATING] As Nullable(Of Decimal), ByVal [HAPPINESSRATING] As Nullable(Of Decimal), ByVal [NEUTRALRATING] As Nullable(Of Decimal), ByVal [SADNESSRATING] As Nullable(Of Decimal), ByVal [SURPRISERATING] As Nullable(Of Decimal), ByVal [CHANGEAGENTID] As Nullable(Of System.Guid), ByVal [CURRENTDATE] As Nullable(Of Date), Optional ByRef returnIntValue As Integer = 0, Optional ByVal timeout As Integer = 0, Optional ByVal tran As SQLClient.SQLTransaction = Nothing) As Integer

            Dim cmd As System.Data.SqlClient.SqlCommand
            cmd = CreateSQLCommand(conn, [CONSTITUENTID], [PREDICTEDGENDERCODE], [ESTIMATEDAGE], [ANGERRATING], [CONTEMPTRATING], [DISGUSTRATING], [FEARRATING], [HAPPINESSRATING], [NEUTRALRATING], [SADNESSRATING], [SURPRISERATING], [CHANGEAGENTID], [CURRENTDATE], timeout)
            If tran IsNot Nothing Then
                cmd.Transaction = tran
            End If
            Dim rowCount As Integer = cmd.ExecuteNonQuery()
            Dim returnObjectValue As Object = cmd.Parameters.Item(0).Value

            If Not IsDBNull(returnObjectValue) Then
                returnIntValue = CInt(returnObjectValue)
            Else
                returnIntValue = 0
            End If





            Return rowCount
        End Function


    End Module
End Namespace

